- name: Setup NodeJs Repos
  ansible.builtin.shell: exit 1

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Include App Pre Setup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-pre-setup

- name: Install NodeJS dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Include SystemD
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd
