global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:



rule_files:
  - alert-rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["44.201.6.234:9100"]


