global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
 alertmanagers:
    - static_configs:
        - targets:



rule_files:
  - alert-rules.yml

#scrape_configs:
# - job_name: "prometheus"
 #   static_configs:
  #    - targets:
   #         - "34.227.195.249:9100"

scrape_configs:
  - job_name: ec2-nodes
    ec2_sd_configs:
      - region: "us-east-1"
        port: 9100
        filters:
          - name: "tag:Monitor"
            values: [ "Yes" ]


